config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/foods", to: "food_items#index", as: "foods"
  post "/foods", to: "food_items#create"
  get "/foods/new", to: "food_items#new", as: "new_food"
  get "/foods/:id/edit", to: "food_items#edit", as: "edit_food"
  get "/foods/:id", to: "food_items#show", as: "food"
  put "/foods/:id", to: "food_items#update"
  delete "/foods/:id", to: "food_items#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beverage.rb
class Beverage < ApplicationRecord
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
  end
end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController

end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  def index
    @foods = FoodItem.all
  end

  def show
    @food = FoodItem.find(params[:id])
  end

  def new
  end

  def create
    FoodItem.create(name: params[:food], calories: params[:calories])
    redirect_to foods_path
  end

  def destroy
    FoodItem.find(params[:id]).destroy
    redirect_to foods_path
  end

  def edit
    @food = FoodItem.find(params[:id])
  end

  def update
    @food = FoodItem.find(params[:id])
    @food.name = params[:food]
    @food.calories = params[:calories]
    @food.save

    redirect_to food_path(@food.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/food_items/edit.html.erb
<form action="<%= food_path %>" method="POST">
  <input name="_method" type="hidden" value="PUT">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="food">Food</label>
  <input type="text" name="food" id="food" value="<%= @food.name %>">
  <label for="calories">Calories</label>
  <input type="number" name="calories" id="calories" step="0.01" value="<%= @food.calories %>">
  <input type="submit" value="Submit">
</form>

app/views/food_items/index.html.erb
<h1>Foods</h1>
<button><%= link_to "New Food", new_food_path %></button>
<ul>
  <% for food in @foods %>
    <li><%= link_to food.id, food_path(food.id) %>: <%= food.name %> - <%= food.calories %> Calories <button><%= link_to "X", food_path(food.id), method: :delete %></button></li>
  <% end %>
</ul>

app/views/food_items/new.html.erb
<form action="<%= foods_path %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="food">Food</label>
  <input type="text" name="food" id="food">
  <label for="calories">Calories</label>
  <input type="number" name="calories" id="calories" step="0.01">
  <input type="submit" value="Submit">
</form>

app/views/food_items/show.html.erb
<h1><%= @food.id %>: <%= @food.name %></h1>
<h2><%= @food.calories %> Calories</h2>

<%= link_to "Edit", edit_food_path(@food.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "Home", foods_path%>
    <%= yield %>
  </body>
</html>